
version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "0.0.0.0:1050:1050"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
